[General]
; Note: Delete the cached TLE data to force a refresh and change the satellite list
; Warning: The more TLEs to load the longer it will take the program to load!

tle_urls = https://celestrak.org/norad/elements/weather.txt, https://celestrak.org/norad/elements/amateur.txt

; If you're interested in other satellites and weird orbit shapes
; https://celestrak.org/norad/elements/gnss.txt
; https://celestrak.org/norad/elements/geo.txt

[Tracker]
; If no satellites selected, the fallback will be the first element of the weather.txt list.
; Farewell to NOAA 15, 18, and 19. APT sounded too good <3
; satellites = NOAA 19,NOAA 15,NOAA 18
satellites = METEOR-M2 3, METEOR-M2 4

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; You can set the ground station coordinates here. The format is "latitude, longitude".         ;;;;
; You can go to google maps, right click and directly copy paste the coordinates.               ;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; ground_station = 43.28360856004391, -2.9443897413718707             ; Bilbao, Spain
ground_station = 49.94599740987948, 11.57125315174145               ; Bayreuth, Germany
; ground_station = 42.355301837248014, -71.05567947522265             ; Boston, USA
; ground_station = 54.597281792832, -5.930144529938375                ; Belfast, UK

ground_station_label = Bayreuth ; Leave this empty to disable the label

orbit_duration = 180        ; The number of minutes predicted for the orbit.
orbit_style    = Lines    ; The style of the orbit. Options: "Lines", "Points"


[Visuals]
accent_color = 1EFF3CFF ; Hacker green
